"""Auto-generated by tools/load_xmi.py — recreates the loaded model."""

from pyecore.resources import ResourceSet, URI


def _all_packages(package):
    yield package
    for sub in package.eSubpackages:
        yield from _all_packages(sub)


rset = ResourceSet()
_packages = []
for _p in _all_packages(rset.get_resource(URI('languages/sysmlv2/SysML.ecore')).contents[0]):
    if _p.nsURI:
        rset.metamodel_registry[_p.nsURI] = _p
    _packages.append(_p)
rset.metamodel_registry['http://www.eclipse.org/syson/sysml'] = next(p for p in _packages if p.nsURI == 'https://www.omg.org/spec/SysML/20250201')


def _find(name):
    for _p in _packages:
        classifier = _p.getEClassifier(name)
        if classifier is not None:
            return classifier
    raise KeyError('Unknown classifier: ' + name)


# --- Classifiers ---
AcceptActionUsage = _find('AcceptActionUsage')
ActionDefinition = _find('ActionDefinition')
EndFeatureMembership = _find('EndFeatureMembership')
FeatureDirectionKind = _find('FeatureDirectionKind')
FeatureMembership = _find('FeatureMembership')
FeatureTyping = _find('FeatureTyping')
FeatureValue = _find('FeatureValue')
ItemDefinition = _find('ItemDefinition')
LiteralString = _find('LiteralString')
Membership = _find('Membership')
Namespace = _find('Namespace')
NamespaceImport = _find('NamespaceImport')
OwningMembership = _find('OwningMembership')
Package = _find('Package')
ParameterMembership = _find('ParameterMembership')
PerformActionUsage = _find('PerformActionUsage')
ReferenceSubsetting = _find('ReferenceSubsetting')
ReferenceUsage = _find('ReferenceUsage')
StateDefinition = _find('StateDefinition')
StateSubactionKind = _find('StateSubactionKind')
StateSubactionMembership = _find('StateSubactionMembership')
StateUsage = _find('StateUsage')
SuccessionAsUsage = _find('SuccessionAsUsage')
TransitionFeatureKind = _find('TransitionFeatureKind')
TransitionFeatureMembership = _find('TransitionFeatureMembership')
TransitionUsage = _find('TransitionUsage')

# --- Object creation and attributes ---
namespace_0 = Namespace(elementId='2465fe3a-6fd2-471a-9ea4-4ced1cf791ac')
owningmembership_1 = OwningMembership(elementId='2ceed280-05cf-4d90-bdbc-e27576316ca3')
package_2 = Package(declaredName='SimpleSimulationPackage', elementId='2ca99d42-3b4f-4c1d-a034-dad547fdaab7')
namespaceimport_3 = NamespaceImport(elementId='2be0967a-4dd9-4c97-82b0-a37850762144')
owningmembership_4 = OwningMembership(elementId='2bc1840b-6527-4ded-83d1-57a898b9462c')
owningmembership_5 = OwningMembership(elementId='546a8d4a-b355-44d7-9165-27e889de7501')
owningmembership_6 = OwningMembership(elementId='3c091882-08e2-4343-9d41-22426cdb11ec')
owningmembership_7 = OwningMembership(elementId='4b0b800d-d823-41a0-85c2-6f53af354d66')
owningmembership_8 = OwningMembership(elementId='8078151c-41cb-4f9b-aa4c-f4735b0748fd')
actiondefinition_9 = ActionDefinition(declaredName='Print', elementId='5af290f5-25be-4c74-85ae-6467fce20ea9')
featuremembership_10 = FeatureMembership(elementId='57fd0c28-f3c2-45a5-8d18-dd71fc6fa043')
referenceusage_11 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, declaredName='msg', elementId='e54b3203-9366-4a26-ac58-87611c13317d')
featuretyping_12 = FeatureTyping(elementId='1fb87066-a106-48ce-bb3c-86e6d3f43990')
itemdefinition_13 = ItemDefinition(declaredName='IdleTrans', elementId='5724a4c1-d70e-46d6-9e6a-4fc3be304a25')
itemdefinition_14 = ItemDefinition(declaredName='NextTrans', elementId='e3e6b8dd-7ca3-4a14-86ee-11e7a055292c')
statedefinition_15 = StateDefinition(declaredName='MySimulationDefinition', elementId='4d773355-7ea5-49e6-a17f-bb96c60fe2fd')
statesubactionmembership_16 = StateSubactionMembership(kind=StateSubactionKind.getEEnumLiteral('entry'), elementId='946b1779-f08a-422a-ba5a-ccf277c9ddef')
featuremembership_17 = FeatureMembership(elementId='91db7382-876e-495d-80fb-57b93ba5f9e3')
featuremembership_18 = FeatureMembership(elementId='c1fba209-7195-4c8f-b6e9-84e6c0138153')
featuremembership_19 = FeatureMembership(elementId='29904e3c-a01b-4aa2-98e1-c27842c87204')
featuremembership_20 = FeatureMembership(elementId='9b1710b6-2e43-4f11-9014-1c2079db7d01')
featuremembership_21 = FeatureMembership(elementId='a9907e6e-4368-4ce5-a59a-cc3f08878968')
performactionusage_22 = PerformActionUsage(isComposite=True, declaredName='pEntry', elementId='e5ef3a8b-0679-4679-b012-2828963bb4dd')
featuremembership_23 = FeatureMembership(elementId='f25a23f6-1e30-4a27-aff0-eb80093c7200')
featuretyping_24 = FeatureTyping(elementId='44b15b04-9cf4-43cf-8400-c9b2aa0a2b7b')
referenceusage_25 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, declaredName='msg', elementId='ab6b61e3-0ca8-44b0-ac71-ecd6573704d8')
featurevalue_26 = FeatureValue(elementId='f278492c-a3e1-4b46-9035-91d54c0ee88b')
literalstring_27 = LiteralString(value='Entry', elementId='53c768cf-502d-4f5d-b612-5890f04b7f7d')
transitionusage_28 = TransitionUsage(isComposite=True, elementId='c56f2cac-13ca-417b-ba48-3218dfc70a2b')
membership_29 = Membership(elementId='c4de1297-b6f9-469c-9298-68cb9aeba34f')
owningmembership_30 = OwningMembership(elementId='972bb918-0e31-4964-a8f4-f0bf301de033')
parametermembership_31 = ParameterMembership(elementId='e213095b-ceba-4a57-b389-6042b09181cc')
successionasusage_32 = SuccessionAsUsage(isComposite=True, elementId='f31e85a2-6622-47ee-857a-bab92b90c263')
endfeaturemembership_33 = EndFeatureMembership(elementId='9f890e81-c13e-4277-84d8-c5f0594dbc6a')
endfeaturemembership_34 = EndFeatureMembership(elementId='635915a8-9ca0-4052-9a48-c5d4059b7d08')
referenceusage_35 = ReferenceUsage(isEnd=True, elementId='0806d049-0ef4-4960-aec8-a69ccf6aaa43')
referenceusage_36 = ReferenceUsage(isComposite=True, isEnd=True, elementId='5bc5cc95-b73e-4414-8a21-613bc6ee71cb')
referencesubsetting_37 = ReferenceSubsetting(elementId='03606b74-18ac-42bd-a65c-47b77652d6bb')
referenceusage_38 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, elementId='9b6a54fe-a36c-4fbc-9bc4-490ecea6f329')
stateusage_39 = StateUsage(isComposite=True, declaredName='Idle', elementId='bc00bb46-bb2c-4d20-8e29-b62a9e6468e7')
transitionusage_40 = TransitionUsage(isComposite=True, elementId='00ff654b-66f3-48dc-a95e-30a5469a24e5')
membership_41 = Membership(elementId='a4ef84ad-dc1f-427f-a2f1-16e30d58d6da')
transitionfeaturemembership_42 = TransitionFeatureMembership(kind=TransitionFeatureKind.getEEnumLiteral('trigger'), elementId='8c7fd863-fd73-4d7d-85a2-457d13882523')
transitionfeaturemembership_43 = TransitionFeatureMembership(elementId='33b1a8ff-2557-4d6c-8f63-52da90643f0e')
owningmembership_44 = OwningMembership(elementId='a88cb103-b348-4d5b-8ac4-99c4852292df')
parametermembership_45 = ParameterMembership(elementId='320db8a2-f8e2-4cca-b01d-10b0db3e8ad8')
parametermembership_46 = ParameterMembership(elementId='aaa8a9c4-c342-41a0-a3a5-0754f14fe241')
acceptactionusage_47 = AcceptActionUsage(isComposite=True, elementId='6d85d066-c219-49d9-a40b-98df2d9de6ed')
parametermembership_48 = ParameterMembership(elementId='6e56ba40-5793-4836-ad8d-d97521c1e73c')
referenceusage_49 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, elementId='616e3a68-7584-4659-b842-f003390169c1')
featuretyping_50 = FeatureTyping(elementId='039b1e6d-5939-48ef-a1ba-4634a9f17b42')
performactionusage_51 = PerformActionUsage(isComposite=True, declaredName='pIdle', elementId='3db16955-1692-4e9c-883b-bafa37978380')
featuremembership_52 = FeatureMembership(elementId='8a3b4677-7a0c-4cd0-a232-b835a6e8c09b')
featuretyping_53 = FeatureTyping(elementId='d4473252-0fae-453c-865f-fc47bdb81f19')
referenceusage_54 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, declaredName='msg', elementId='49cf7bb7-0a07-400d-8d1e-9ebde4abacad')
featurevalue_55 = FeatureValue(elementId='f565c836-fba6-4171-903e-4b58425626d3')
literalstring_56 = LiteralString(value='Hello World', elementId='5a51b4c4-a7c4-4e75-9477-762e3763f352')
successionasusage_57 = SuccessionAsUsage(isComposite=True, elementId='468cce83-54d7-450c-b869-0c61d1a8265c')
endfeaturemembership_58 = EndFeatureMembership(elementId='8a78a0fa-6c9c-499d-a46e-3a35836d5955')
endfeaturemembership_59 = EndFeatureMembership(elementId='68783779-da59-4c96-a086-411ec01377c4')
referenceusage_60 = ReferenceUsage(isEnd=True, elementId='e001c6f6-9fad-43a4-aeab-e8f11058fef6')
referenceusage_61 = ReferenceUsage(isComposite=True, isEnd=True, elementId='0cee313b-c2a8-4ed8-81a5-4ab7d3730ccd')
referencesubsetting_62 = ReferenceSubsetting(elementId='1c86ab03-0b40-414e-8f59-394229a12b43')
referenceusage_63 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, elementId='8bbad22a-d576-4956-b3da-1d9d7247ca7e')
referenceusage_64 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, elementId='bfbd190e-0ba2-4d33-92e0-d2e506582c55')
stateusage_65 = StateUsage(isComposite=True, declaredName='Next', elementId='01bb746b-1f0e-4813-8ce6-aeac3f586fa7')
transitionusage_66 = TransitionUsage(isComposite=True, elementId='8dac4ea6-8db4-40f1-9a49-6cfd4a371997')
membership_67 = Membership(elementId='35c113d3-0065-41d8-9637-494b418611c8')
transitionfeaturemembership_68 = TransitionFeatureMembership(kind=TransitionFeatureKind.getEEnumLiteral('trigger'), elementId='e0b0b866-bb7e-401f-943f-23549ea581d7')
transitionfeaturemembership_69 = TransitionFeatureMembership(elementId='d1887e79-3ba4-4e84-8ab9-4bfad06c083e')
owningmembership_70 = OwningMembership(elementId='5833d252-3be1-4ec0-92c2-88401bb5daec')
parametermembership_71 = ParameterMembership(elementId='b7268d45-8568-4178-9e74-57aea573d250')
parametermembership_72 = ParameterMembership(elementId='d9f14f09-557d-43d3-98ce-6cb3a6cedea3')
acceptactionusage_73 = AcceptActionUsage(isComposite=True, elementId='6ea68f3d-3db0-4f7b-a380-2e52252e3186')
parametermembership_74 = ParameterMembership(elementId='30ffe8f5-9077-4c29-bdb3-69ac9b578726')
referenceusage_75 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, elementId='dea75e9f-1c65-4daa-a63d-46a8d2ec9ce2')
featuretyping_76 = FeatureTyping(elementId='562e7ea0-8d0f-4f51-939d-6813d2d8df4d')
performactionusage_77 = PerformActionUsage(isComposite=True, declaredName='pNext', elementId='304a0fff-c265-4df2-aacd-183615c2b9d4')
featuremembership_78 = FeatureMembership(elementId='7f7d86ca-0c70-4b4b-8f66-91d124f85228')
featuretyping_79 = FeatureTyping(elementId='77b732d2-63b2-43ba-9903-d97b9cedb8a3')
referenceusage_80 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, declaredName='msg', elementId='b1e379e8-f047-4a92-99fe-f7cb15265ce7')
featurevalue_81 = FeatureValue(elementId='a98501e3-729d-4c0d-a0d0-4c88e9c9d4ae')
literalstring_82 = LiteralString(value='Next Please', elementId='8b2d7dda-4a0f-4b61-b46d-3872c8e2b0f4')
successionasusage_83 = SuccessionAsUsage(isComposite=True, elementId='0d5138e0-200c-4787-885b-05e2b2ccd77e')
endfeaturemembership_84 = EndFeatureMembership(elementId='edab35a9-a751-46dd-8067-72ceb010d291')
endfeaturemembership_85 = EndFeatureMembership(elementId='409b9289-1c0d-4e01-946a-16cdb19882e8')
referenceusage_86 = ReferenceUsage(isEnd=True, elementId='a5a31ce8-b340-478d-a5ab-ce343c3499ab')
referenceusage_87 = ReferenceUsage(isComposite=True, isEnd=True, elementId='f382dc68-e70c-4dd2-8785-075ccb1e7ff7')
referencesubsetting_88 = ReferenceSubsetting(elementId='913a06da-ae35-445a-96bf-edc795fe4bd6')
referenceusage_89 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, elementId='e961ab4d-f61f-4eb3-93b8-8fb8e3885ff1')
referenceusage_90 = ReferenceUsage(direction=FeatureDirectionKind.getEEnumLiteral('in'), isComposite=True, elementId='35f5073d-942b-48dc-8813-5d8182427d1b')
stateusage_91 = StateUsage(isComposite=True, declaredName='main', elementId='3e3357a1-c35b-4d30-a5fb-16980bb19594')
featuretyping_92 = FeatureTyping(elementId='500e34ab-7f5c-4a12-a9d3-18dd3ec3bae8')

# --- Containment (model tree) ---
namespace_0.ownedRelationship.append(owningmembership_1)
owningmembership_1.ownedRelatedElement.append(package_2)
package_2.ownedRelationship.append(namespaceimport_3)
package_2.ownedRelationship.append(owningmembership_4)
package_2.ownedRelationship.append(owningmembership_5)
package_2.ownedRelationship.append(owningmembership_6)
package_2.ownedRelationship.append(owningmembership_7)
package_2.ownedRelationship.append(owningmembership_8)
owningmembership_4.ownedRelatedElement.append(actiondefinition_9)
actiondefinition_9.ownedRelationship.append(featuremembership_10)
featuremembership_10.ownedRelatedElement.append(referenceusage_11)
referenceusage_11.ownedRelationship.append(featuretyping_12)
owningmembership_5.ownedRelatedElement.append(itemdefinition_13)
owningmembership_6.ownedRelatedElement.append(itemdefinition_14)
owningmembership_7.ownedRelatedElement.append(statedefinition_15)
statedefinition_15.ownedRelationship.append(statesubactionmembership_16)
statedefinition_15.ownedRelationship.append(featuremembership_17)
statedefinition_15.ownedRelationship.append(featuremembership_18)
statedefinition_15.ownedRelationship.append(featuremembership_19)
statedefinition_15.ownedRelationship.append(featuremembership_20)
statedefinition_15.ownedRelationship.append(featuremembership_21)
statesubactionmembership_16.ownedRelatedElement.append(performactionusage_22)
performactionusage_22.ownedRelationship.append(featuremembership_23)
performactionusage_22.ownedRelationship.append(featuretyping_24)
featuremembership_23.ownedRelatedElement.append(referenceusage_25)
referenceusage_25.ownedRelationship.append(featurevalue_26)
featurevalue_26.ownedRelatedElement.append(literalstring_27)
featuremembership_17.ownedRelatedElement.append(transitionusage_28)
transitionusage_28.ownedRelationship.append(membership_29)
transitionusage_28.ownedRelationship.append(owningmembership_30)
transitionusage_28.ownedRelationship.append(parametermembership_31)
owningmembership_30.ownedRelatedElement.append(successionasusage_32)
successionasusage_32.ownedRelationship.append(endfeaturemembership_33)
successionasusage_32.ownedRelationship.append(endfeaturemembership_34)
endfeaturemembership_33.ownedRelatedElement.append(referenceusage_35)
endfeaturemembership_34.ownedRelatedElement.append(referenceusage_36)
referenceusage_36.ownedRelationship.append(referencesubsetting_37)
parametermembership_31.ownedRelatedElement.append(referenceusage_38)
featuremembership_18.ownedRelatedElement.append(stateusage_39)
featuremembership_19.ownedRelatedElement.append(transitionusage_40)
transitionusage_40.ownedRelationship.append(membership_41)
transitionusage_40.ownedRelationship.append(transitionfeaturemembership_42)
transitionusage_40.ownedRelationship.append(transitionfeaturemembership_43)
transitionusage_40.ownedRelationship.append(owningmembership_44)
transitionusage_40.ownedRelationship.append(parametermembership_45)
transitionusage_40.ownedRelationship.append(parametermembership_46)
transitionfeaturemembership_42.ownedRelatedElement.append(acceptactionusage_47)
acceptactionusage_47.ownedRelationship.append(parametermembership_48)
parametermembership_48.ownedRelatedElement.append(referenceusage_49)
referenceusage_49.ownedRelationship.append(featuretyping_50)
transitionfeaturemembership_43.ownedRelatedElement.append(performactionusage_51)
performactionusage_51.ownedRelationship.append(featuremembership_52)
performactionusage_51.ownedRelationship.append(featuretyping_53)
featuremembership_52.ownedRelatedElement.append(referenceusage_54)
referenceusage_54.ownedRelationship.append(featurevalue_55)
featurevalue_55.ownedRelatedElement.append(literalstring_56)
owningmembership_44.ownedRelatedElement.append(successionasusage_57)
successionasusage_57.ownedRelationship.append(endfeaturemembership_58)
successionasusage_57.ownedRelationship.append(endfeaturemembership_59)
endfeaturemembership_58.ownedRelatedElement.append(referenceusage_60)
endfeaturemembership_59.ownedRelatedElement.append(referenceusage_61)
referenceusage_61.ownedRelationship.append(referencesubsetting_62)
parametermembership_45.ownedRelatedElement.append(referenceusage_63)
parametermembership_46.ownedRelatedElement.append(referenceusage_64)
featuremembership_20.ownedRelatedElement.append(stateusage_65)
featuremembership_21.ownedRelatedElement.append(transitionusage_66)
transitionusage_66.ownedRelationship.append(membership_67)
transitionusage_66.ownedRelationship.append(transitionfeaturemembership_68)
transitionusage_66.ownedRelationship.append(transitionfeaturemembership_69)
transitionusage_66.ownedRelationship.append(owningmembership_70)
transitionusage_66.ownedRelationship.append(parametermembership_71)
transitionusage_66.ownedRelationship.append(parametermembership_72)
transitionfeaturemembership_68.ownedRelatedElement.append(acceptactionusage_73)
acceptactionusage_73.ownedRelationship.append(parametermembership_74)
parametermembership_74.ownedRelatedElement.append(referenceusage_75)
referenceusage_75.ownedRelationship.append(featuretyping_76)
transitionfeaturemembership_69.ownedRelatedElement.append(performactionusage_77)
performactionusage_77.ownedRelationship.append(featuremembership_78)
performactionusage_77.ownedRelationship.append(featuretyping_79)
featuremembership_78.ownedRelatedElement.append(referenceusage_80)
referenceusage_80.ownedRelationship.append(featurevalue_81)
featurevalue_81.ownedRelatedElement.append(literalstring_82)
owningmembership_70.ownedRelatedElement.append(successionasusage_83)
successionasusage_83.ownedRelationship.append(endfeaturemembership_84)
successionasusage_83.ownedRelationship.append(endfeaturemembership_85)
endfeaturemembership_84.ownedRelatedElement.append(referenceusage_86)
endfeaturemembership_85.ownedRelatedElement.append(referenceusage_87)
referenceusage_87.ownedRelationship.append(referencesubsetting_88)
parametermembership_71.ownedRelatedElement.append(referenceusage_89)
parametermembership_72.ownedRelatedElement.append(referenceusage_90)
owningmembership_8.ownedRelatedElement.append(stateusage_91)
stateusage_91.ownedRelationship.append(featuretyping_92)

# --- Cross references ---
# namespaceimport_3.importedNamespace -> external proxy 'kermllibrary:///b2c6dd37-2084-3ce4-9ce2-580fdf30629c#7972bd48-98cd-42fe-9841-c239e8dfae1a'
# featuretyping_12.type -> external proxy 'kermllibrary:///b2c6dd37-2084-3ce4-9ce2-580fdf30629c#d3eebeee-c4b6-4944-b452-f12d56c0f378'
featuretyping_12.typedFeature = referenceusage_11
featuretyping_24.type = actiondefinition_9
featuretyping_24.typedFeature = performactionusage_22
membership_29.memberElement = performactionusage_22
referencesubsetting_37.referencedFeature = stateusage_39
referencesubsetting_37.subsettingFeature = referenceusage_36
membership_41.memberElement = stateusage_39
featuretyping_50.type = itemdefinition_13
featuretyping_50.typedFeature = referenceusage_49
featuretyping_53.type = actiondefinition_9
featuretyping_53.typedFeature = performactionusage_51
referencesubsetting_62.referencedFeature = stateusage_65
referencesubsetting_62.subsettingFeature = referenceusage_61
membership_67.memberElement = stateusage_65
featuretyping_76.type = itemdefinition_14
featuretyping_76.typedFeature = referenceusage_75
featuretyping_79.type = actiondefinition_9
featuretyping_79.typedFeature = performactionusage_77
referencesubsetting_88.referencedFeature = stateusage_39
referencesubsetting_88.subsettingFeature = referenceusage_87
featuretyping_92.type = statedefinition_15
featuretyping_92.typedFeature = stateusage_91

# --- Model roots ---
roots = [namespace_0]
